@isTest
public class UtilityTest {

    static testMethod void testIt() {
    
        Utility g = new Utility();
        g.runMe();
    
    }

        static testMethod void testIt2() {
    
        Utility g = new Utility();
        g.runMe2();
    
    }
    
        static testMethod void testIt3() {
    
        Utility g = new Utility();
        g.runMe3();
    
    }
    
        static testMethod void testIt4() {
    
        Utility g = new Utility();
        g.runMe4();
    
    }
    
}